import { Platform } from 'react-native';
import { Audio } from 'expo-av';

class VoiceService {
  constructor() {
    this.recognition = null;
    this.soundObject = null;
  }

  initWebSpeech(onResult, onStart, onEnd, onError) {
    if (Platform.OS !== 'web') return null;

    if (typeof window !== 'undefined') {
      const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
      if (SpeechRecognition) {
        const recognition = new SpeechRecognition();
        recognition.continuous = false;
        recognition.interimResults = false;
        recognition.lang = 'hi-IN';

        recognition.onstart = () => {
          if (onStart) onStart();
        };

        recognition.onresult = (event) => {
          const transcript = event.results[0][0].transcript;
          if (onResult) onResult(transcript);
        };

        recognition.onerror = (event) => {
          console.warn('Speech recognition error:', event.error);
          if (onError) onError(event.error);
        };

        recognition.onend = () => {
          if (onEnd) onEnd();
        };

        this.recognition = recognition;
        return recognition;
      }
    }
    return null;
  }

  startListening() {
    if (this.recognition) {
      try {
        this.recognition.start();
      } catch (err) {
        console.warn('Recognition start error:', err);
      }
    }
  }

  stopListening() {
    if (this.recognition) {
      try {
        this.recognition.stop();
      } catch (err) {
        console.warn('Recognition stop error:', err);
      }
    }
  }

  async playTTSAudio(base64AudioUrl, fallbackText) {
    let audioPlayed = false;

    // 1. Try to play base64 MP3 (Neural voice generated by backend)
    if (base64AudioUrl) {
      try {
        if (Platform.OS === 'web' && typeof window !== 'undefined') {
          const webAudio = new window.Audio(base64AudioUrl);
          await new Promise((resolve, reject) => {
            webAudio.onended = resolve;
            webAudio.onerror = reject;
            webAudio.play().catch(reject);
          });
          audioPlayed = true;
        } else {
          // Native mobile via expo-av
          if (this.soundObject) {
            await this.soundObject.unloadAsync().catch(() => {});
          }
          const { sound } = await Audio.Sound.createAsync(
            { uri: base64AudioUrl },
            { shouldPlay: true }
          );
          this.soundObject = sound;
          await sound.playAsync();
          audioPlayed = true;
        }
      } catch (e) {
        console.warn('Base64 audio playback failed, using browser TTS fallback:', e);
        audioPlayed = false;
      }
    }

    // 2. Fallback: Browser Web SpeechSynthesis (if audio didn't play)
    if (!audioPlayed && fallbackText) {
      this.speakText(fallbackText);
    }
  }

  /**
   * Speaks text aloud using the browser's built-in SpeechSynthesis API.
   * Works as a reliable fallback when backend TTS audio is unavailable.
   */
  speakText(text, lang = 'hi-IN') {
    if (Platform.OS === 'web' && typeof window !== 'undefined' && 'speechSynthesis' in window) {
      // Cancel any ongoing speech first
      window.speechSynthesis.cancel();

      const utterance = new window.SpeechSynthesisUtterance(text);
      utterance.lang = lang;
      utterance.rate = 1.0;
      utterance.pitch = 1.0;
      utterance.volume = 1.0;

      // Try to find a Hindi voice, otherwise use default
      const voices = window.speechSynthesis.getVoices();
      const hindiVoice = voices.find(v => v.lang.startsWith('hi'));
      if (hindiVoice) {
        utterance.voice = hindiVoice;
      }

      window.speechSynthesis.speak(utterance);
    }
  }
}

export const voiceService = new VoiceService();
