import { Platform } from 'react-native';
import { Audio } from 'expo-av';

class VoiceService {
  constructor() {
    this.recognition = null;
    this.soundObject = null;
  }

  initWebSpeech(onResult, onStart, onEnd, onError) {
    if (Platform.OS !== 'web') return null;

    if (typeof window !== 'undefined') {
      const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
      if (SpeechRecognition) {
        const recognition = new SpeechRecognition();
        recognition.continuous = false;
        recognition.interimResults = false;
        recognition.lang = 'hi-IN';

        recognition.onstart = () => {
          if (onStart) onStart();
        };

        recognition.onresult = (event) => {
          const transcript = event.results[0][0].transcript;
          if (onResult) onResult(transcript);
        };

        recognition.onerror = (event) => {
          console.warn('Speech recognition error:', event.error);
          if (onError) onError(event.error);
        };

        recognition.onend = () => {
          if (onEnd) onEnd();
        };

        this.recognition = recognition;
        return recognition;
      }
    }
    return null;
  }

  startListening() {
    if (this.recognition) {
      try {
        this.recognition.start();
      } catch (err) {
        console.warn('Recognition start error:', err);
      }
    }
  }

  stopListening() {
    if (this.recognition) {
      try {
        this.recognition.stop();
      } catch (err) {
        console.warn('Recognition stop error:', err);
      }
    }
  }

  async playTTSAudio(base64AudioUrl, fallbackText) {
    try {
      // 1. Play base64 MP3 (Neural voice generated by backend)
      if (base64AudioUrl) {
        if (Platform.OS === 'web' && typeof Audio !== 'undefined') {
          const webAudio = new window.Audio(base64AudioUrl);
          await webAudio.play();
          return;
        } else {
          // Native mobile via expo-av
          if (this.soundObject) {
            await this.soundObject.unloadAsync().catch(() => {});
          }
          const { sound } = await Audio.Sound.createAsync(
            { uri: base64AudioUrl },
            { shouldPlay: true }
          );
          this.soundObject = sound;
          await sound.playAsync();
          return;
        }
      }

      // 2. Fallback: Browser Web SpeechSynthesis
      if (Platform.OS === 'web' && typeof window !== 'undefined' && 'speechSynthesis' in window && fallbackText) {
        const utterance = new window.SpeechSynthesisUtterance(fallbackText);
        utterance.lang = 'hi-IN';
        utterance.rate = 1.0;
        window.speechSynthesis.speak(utterance);
      }
    } catch (e) {
      console.warn('Audio playback notice:', e);
    }
  }
}

export const voiceService = new VoiceService();
